### ISSUE TITLE
Invalid String exit character

### ISSUE THREAD

**Issue by garritfra** [antimony-lang/antimony#27]
Double quoted strings could probably be ended by single quoted, and vice versa.

Example:

`"It's a test"` fails, since `'` is considered as an exit character for the string

https://github.com/antimony-lang/antimony/blob/5e4f0a15c0b5c1878054310024864f8b97bddf27/src/lexer/mod.rs#L412-L424

**Comment by YerinAlexey** [comment]
I'll take it

**Comment by YerinAlexey** [comment]
Sent a patch: https://lists.sr.ht/~garritfra/antimony/patches/20657

**Comment by garritfra** [comment]
Fixed by 0cbdc88
