### ISSUE TITLE
Constructors not valid as function parameters

### ISSUE THREAD

**Issue by garritfra** [antimony-lang/antimony#29]
This throws an error

```
append_todo(new Todo {
   name: text
   checked: false 
}
```

```
Error: "Token BraceClose not found, found Token { kind: Keyword(New), len: 3, raw: \"new\", pos: Position { line: 19, offset: 19, raw: 391 } }\n\"w Todo {\""
```

**Comment by YerinAlexey** [comment]
> ```
> Error: "Token BraceClose not found, found Token { kind: Keyword(New), len: 3, raw: \"new\", pos: Position { line: 19, offset: 19, raw: 391 } }\n\"w Todo {\""
> ```

Hm, that error is very weird, I'll check the parser

**Comment by garritfra** [comment]
I think "new" is just not an expected token by parse_argument_list. Should be easy to fix by adding it.

**Comment by YerinAlexey** [comment]
Why don't we just use `parse_expression` there and make it deal with all the stuff?

**Comment by garritfra** [comment]
I actually thought we did that. At least that's what makes the most sense.

Alexey <notifications@github.com> schrieb am So., 28. Feb. 2021, 11:04 AM:
